(define (macroexpand exp)
  (cond ((variable? exp)
	 exp)
	((null? exp)
	 '())
	((pair? exp)
	 (cond ((eq? (car exp) 'lambda)
		`(lambda ,(macroexpand-formals (cadr exp))
		   ,(macroexpand (caddr exp))))
	       ((eq? (car exp) 'cons)
		`(cons ,(macroexpand (cadr exp))
		       ,(macroexpand (caddr exp))))
	       (else
		`(,(macroexpand (car exp))
		  ,(macroexpand-operands (cdr exp))))))
	(else
	 (error "Invalid expression syntax" exp))))

(define (macroexpand-operands operands)
  (if (null? operands)
      '()
      `(cons ,(macroexpand (car operands))
	     ,(macroexpand-operands (cdr operands)))))

(define (macroexpand-formals formals)
  (cond ((null? formals)
	 formals)
	((symbol? formals)
	 formals)
	((pair? formals)
	 (if (eq? (car formals) 'cons)
	     (cons (macroexpand-formals (cadr formals))
		   (macroexpand-formals (caddr formals)))
	     (cons (macroexpand-formals (car formals))
		   (macroexpand-formals (cdr formals)))))
	(else
	 (error "Invalid formal parameter tree" formals))))
