#!/bin/bash

SELFDIR=$(dirname $0)

if [ `uname -m` == 'x86_64' ]; then
    HEAP=150000
else
    HEAP=6000
fi

# Explicit tail call here forwards exit state to the parent better
# (notably, an MIT-Scheme run-shell-command calling this script will
# error out in the subsidiary mit-scheme is killed, whereas it would
# return normally otherwise).
exec mit-scheme --heap $HEAP --stack 2000 --batch-mode --no-init-file --load "${SELFDIR}/load.scm" --eval "(begin (dvl-file->fol-file \"$1\") (%exit 0))"
