#!/bin/bash

if [ `uname -m` == 'x86_64' ]; then
    HEAP=100000
else
    HEAP=6000
fi

mit-scheme --compiler --heap $HEAP --stack 2000 --batch-mode --no-init-file --eval '(set! load/suppress-loading-message? #t)' --eval '(begin (load "load") (load "test/load") (show-time run-registered-tests) (newline) (flush-output) (%exit 0))'
