# -*- mode: ruby -*-

task :default => [:test]

task :test do sh <<EOF
mit-scheme \
--compiler \
--batch-mode \
--no-init-file \
--eval '(set! load/suppress-loading-message? #t)' \
--eval '(begin (load "scm/load") (show-time run-registered-tests) (newline) (flush-output) (%exit 0))'
EOF
end
