(define (abstract-equal? thing1 thing2)
  (cond ((eqv? thing1 thing2)
	 #t)
	((and (closure? thing1) (closure? thing2))
	 (and ;; TODO alpha-renaming?
	      (equal? (closure-expression thing1)
		      (closure-expression thing2))
	      (abstract-equal? (closure-env thing1)
			       (closure-env thing2))))
	((and (pair? thing1) (pair? thing2))
	 (and (abstract-equal? (car thing1) (car thing2))
	      (abstract-equal? (cdr thing1) (cdr thing2))))
	((and (abstract-env? thing1) (abstract-env? thing2))
	 (abstract-equal? (abstract-env-bindings thing1)
			  (abstract-env-bindings thing2)))
	(else #f)))

(define (abstract-hash-mod thing modulus)
  (cond ((closure? thing)
	 (modulo (+ (equal-hash-mod (closure-body thing) modulus)
		    (equal-hash-mod (closure-formal thing) modulus)
		    (abstract-hash-mod (closure-env thing) modulus))
		 modulus))
	((pair? thing)
	 (modulo (+ (abstract-hash-mod (car thing) modulus)
		    (abstract-hash-mod (cdr thing) modulus))
		 modulus))
	((abstract-env? thing)
	 (abstract-hash-mod (abstract-env-bindings thing) modulus))
	(else (eqv-hash-mod thing modulus))))

(define make-abstract-hash-table
  (strong-hash-table/constructor abstract-hash-mod abstract-equal? #t))

(define (abstract-union thing1 thing2)
  (cond ((abstract-equal? thing1 thing2)
	 thing1)
	((and (some-boolean? thing1) (some-boolean? thing2))
	 abstract-boolean)
	((and (some-real? thing1) (some-real? thing2))
	 abstract-real)
	((and (closure? thing1) (closure? thing2)
	      (equal? (closure-expression thing1)
		      (closure-expression thing2)))
	 (make-closure (closure-formal thing1)
		       (closure-body thing1)
		       (abstract-union (closure-env thing1)
				       (closure-env thing2))))
	((and (pair? thing1) (pair? thing2))
	 (cons (abstract-union (car thing1) (car thing2))
	       (abstract-union (cdr thing1) (cdr thing2))))
	((and (abstract-env? thing1)
	      (abstract-env? thing2))
	 (make-abstract-env
	  (abstract-union (abstract-env-bindings thing1)
			  (abstract-env-bindings thing2))))
	(else
	 abstract-all)))

(define (solved-abstractly? thing)
  (cond ((null? thing) #t)
	((boolean? thing) #t)
	((real? thing) #t)
	((abstract-boolean? thing) #f)
	((abstract-real? thing) #f)
	((abstract-all? thing) #f)
	((primitive? thing) #t)
	((closure? thing) (solved-abstractly? (closure-env thing)))
	((pair? thing) (and (solved-abstractly? (car thing))
			    (solved-abstractly? (cdr thing))))
	((abstract-env? thing)
	 (every solved-abstractly? (map cdr (abstract-env-bindings thing))))
	(else
	 (error "Invalid abstract value" thing))))

(define (solved-abstract-value->constant thing)
  (cond ((or (null? thing) (boolean? thing) (real? thing))
	 thing)
	((primitive? thing) (primitive-name thing))
	((pair? thing)
	 (list 'cons (solved-abstract-value->constant (car thing))
	       (solved-abstract-value->constant (cdr thing))))
	(else ''void)))

(define (interesting-variable? env)
  (lambda (var)
    (abstract-lookup var env
     (lambda (shape) (not (solved-abstractly? shape)))
     (lambda () #t))))

(define abstract-boolean (list 'abstract-boolean))
(define (abstract-boolean? thing)
  (eq? thing abstract-boolean))
(define (some-boolean? thing)
  (or (boolean? thing)
      (abstract-boolean? thing)))

(define abstract-real (list 'abstract-real))
(define (abstract-real? thing)
  (eq? thing abstract-real))
(define (some-real? thing)
  (or (real? thing)
      (abstract-real? thing)))

(define abstract-all (list 'abstract-all))
(define (abstract-all? thing)
  (eq? thing abstract-all))
