def files
  ["examples",
   "abstract-eval",
   "code-generator",
   "macro",
   "eval",
   "post-processing",
   "primitives",
   "data",
   "env",
   "analysis",
   "abstract-values",
   "nomenclature",
   "load",
  ].map do |base|
  "#{base}.scm"
  end
end

task :workbook do
  sh "enscript -M a4 -fCourier-Bold12 -o workbook.ps --file-align=2 README  --color --highlight #{files.join(" ")}"
end
