#!/bin/bash

### ----------------------------------------------------------------------
### Copyright 2010-2011 National University of Ireland.
### ----------------------------------------------------------------------
### This file is part of DysVunctional Language.
### 
### DysVunctional Language is free software; you can redistribute it and/or modify
### it under the terms of the GNU Affero General Public License as
### published by the Free Software Foundation, either version 3 of the
###  License, or (at your option) any later version.
### 
### DysVunctional Language is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
### 
### You should have received a copy of the GNU Affero General Public License
### along with DysVunctional Language.  If not, see <http://www.gnu.org/licenses/>.
### ----------------------------------------------------------------------

SELFDIR=$(dirname $0)

if [ `uname -m` == 'x86_64' ]; then
    HEAP=50000
else
    HEAP=6000
fi

# Explicit tail call here forwards exit state to the parent better
# (notably, an MIT-Scheme run-shell-command calling this script will
# error out in the subsidiary mit-scheme is killed, whereas it would
# return normally otherwise).
exec mit-scheme --heap $HEAP --batch-mode --no-init-file --load "${SELFDIR}/load.scm" --eval "(begin (vl-run-file \"$1\") (%exit 0))"
